image: jelaniwoods/appdev2021-photogram-associations@sha256:68d9e27ed19cb8e2badbae6a95e5f18789290304fbc9f7892cfc2aa21d10b686

tasks:
  - command: bundle install
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - wingrunr21.vscode-ruby
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
